- name: Create an instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: justin-jul-9-2015
    instance_type: t2.small
    security_group: blog
    image: ami-d05e75b8
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
      register: ec2
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Configure instance
  hosts: launched
  sudo: True
  gather_facts: True
  roles:
    - blog
